export default [
    {
        id: 1,
        createDate: new Date(2023, 0, 1),
        endDate:  new Date(2023, 0, 2),
        markers: [1, 2, 3],
        description: 'Покупка хлеба',
        participants: ['Дима', 'Миша', 'Маша', 'Саша'],
    },
    {
        id: 1,
        createDate: new Date(2024, 0, 5),
        endDate:  new Date(2024, 0, 7),
        markers: [1, 2, 3],
        description: 'Продажа машины',
        participants: ['Полина', 'Кристина', 'Маша', 'Аня'],
    },
    {
        id: 1,
        createDate: new Date(2025, 0, 1),
        endDate:  new Date(2025, 0, 2),
        markers: [1, 2, 3],
        description: 'Магазин',
        participants: ['Егор', 'Миша', 'Света', 'Паша'],
    },
    {
        id: 1,
        createDate: new Date(2025, 0, 1),
        endDate:  new Date(2025, 5, 20),
        markers: [1, 2, 3],
        description: 'Уроки',
        participants: ['Олег', 'Ярослав', 'Валера', 'Саша'],
    },
    {
        id: 1,
        createDate: new Date(2025, 2, 25),
        endDate:  new Date(2025, 5, 6),
        markers: [1, 2, 3],
        description: 'Почитать книгу',
        participants: ['Дима', 'Артем', 'Борис', 'Наташа'],
    },
    {
        id: 1,
        createDate: new Date(2025, 4, 1),
        endDate:  new Date(2025, 5, 30),
        markers: [1, 2, 3],
        description: 'Уборка',
        participants: ['Иван', 'Юра', 'Петя', 'Тая'],
    },
    {
        id: 1,
        createDate: new Date(2025, 4, 28),
        endDate:  new Date(2025, 6, 28),
        markers: [1, 2, 3],
        description: 'Покупка билетов',
        participants: ['Дима', 'Артем', 'Борис', 'Наташа'],
    },
    {
        id: 1,
        createDate: new Date(2021, 0, 1),
        endDate:  new Date(2021, 6, 25),
        markers: [1, 2, 3],
        description: 'Приготовить ужин',
        participants: ['Иван', 'Юра', 'Петя', 'Тая'],
    },
]