export const listTasks = [
    {
        id: 1,
        name: "H.Lorem ipsum dolor sit amet.",
        createDate: new Date(2023, 0, 1),
        endDate:  new Date(2023, 0, 2),
        markers: ['покупка', 'срочно'],
        description: 'Покупка хлеба',
        participants: ['Дима', 'Миша', 'Маша', 'Саша'],
    },
    {
        id: 2,
        name: "F.Lorem ipsum dolor sit amet.",
        createDate: new Date(2024, 0, 5),
        endDate:  new Date(2024, 0, 7),
        markers: ['задание'],
        description: 'Продажа машины',
        participants: ['Полина', 'Кристина', 'Маша', 'Аня'],
    },
    {
        id: 3,
        name: "Z.Lorem ipsum dolor sit amet.",
        createDate: new Date(2025, 0, 1),
        endDate:  new Date(2025, 0, 2),
        markers: ['задание', 'срочно'],
        description: 'Почитать книгу',
        participants: ['Егор', 'Миша', 'Света', 'Паша'],
    },
    {
        id: 4,
        name: "X.Lorem ipsum dolor sit amet.",
        createDate: new Date(2025, 0, 1),
        endDate:  new Date(2025, 5, 20),
        markers: ['задание', 'срочно'],
        description: 'Уроки',
        participants: ['Олег', 'Ярослав', 'Валера', 'Саша'],
    },
    {
        id: 5,
        name: "L.Lorem ipsum dolor sit amet.",
        createDate: new Date(2025, 2, 25),
        endDate:  new Date(2025, 5, 6),
        markers: ['покупка'],
        description: 'Магазин',
        participants: ['Дима', 'Артем', 'Борис', 'Наташа', 'Наташа'],
    },
    {
        id: 6,
        name: "K.Lorem ipsum dolor sit amet.",
        createDate: new Date(2025, 4, 1),
        endDate:  new Date(2025, 5, 30),
        markers: ['задание', 'срочно'],
        description: 'Уборка',
        participants: ['Юра', 'Петя', 'Тая'],
    },
    {
        id: 7,
        name: "O.Lorem ipsum dolor sit amet.",
        createDate: new Date(2025, 4, 28),
        endDate:  new Date(2025, 6, 28),
        markers: ['покупка'],
        description: 'Покупка билетов',
        participants: ['Борис', 'Наташа'],
    },
    {
        id: 8,
        name: "E.Lorem ipsum dolor sit amet.",
        createDate: new Date(2021, 0, 1),
        endDate:  new Date(2021, 6, 25),
        markers: ['задание'],
        description: 'Приготовить ужин',
        participants: ['Иван', 'Юра', 'Петя', 'Тая'],
    },
]